
module.exports = {
  spellcheck: {
    skipWords: [
      'dict',
      'aff',
      'hunspellchecker',
      'hunspell',
      'utils',
      'DTO',
      'VO',
      'Formatter',
      'lang',
      'ecma',
      'ss',
      'tooltip',
      'num',
      'emr',
      'str',
      'res',
      'resp',
      'regx',
      'msg',
      'urls',
      'wong',
      'dayjs',
      'weixin',
      'alipay',
      'openx',
      'wechat',
      'aliy',
      'pathname',
      'pid',
      'uploader',
      'pdf',
      'img',
      'imgs',
      'href',
      'func',
      'oauth',
      'openid',
      'enum',
      'sdk',
      'facebook',
      'weibo',
      'unionid',
      'iframe',
      'uid',
      'jsbridge',
      'dom',
      'unmount',
      'extral',
      'echarts',
      'renderer',
      'helicobacter',
      'headimgurl',
      'osteoarthropathy',
      'gastropathy',
      'calc',
      'hepatorenal',
      'pdfjs',
      'cascader',
      'rect',
      'uri',
      'detections',
      'webpack',
      'Pyloris',
      'echart',
      'Oxygens',
      'Unactivate',
      'antd',
      'tim',
      'ehp',
      'sig',
      'cls',
      'creater',
      'submiter',
    ],
    minLength: 3,
    moduleList: ['echarts', 'echarts/renderers', 'antd', ' eslint', 'react', 'vue'],
    skipIfMatch: [],
    comments: false,
    strings: false,
    identifiers: true,
    templates: false,
  },
};
